#!/usr/bin/env python
#
# Copyright (c) 2012 Citrix Systems, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

import os
import sys
from hashlib import sha1, sha256
import subprocess
import tempfile

PREFIX = 'localuser'

username = sys.argv[1]
hashed_username = '%s-%s' % (PREFIX, sha1(username).hexdigest())
hashed_password = sha256(sys.argv[2]).hexdigest()

name = tempfile.mktemp(dir = '/tmp')
with file(name, 'w') as f:
    f.write(hashed_password)

cmd = subprocess.Popen(['/usr/bin/sec-new-user', hashed_username, name, name])
cmd.communicate('')

sys.exit(cmd.returncode)
